name: Generate snake animation

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"

  workflow_dispatch:

  push:
    branches:
      - master

jobs:
  generate:
    permissions:
      contents: write
    runs-on: windows-latest
    timeout-minutes: 5

    steps:
      - name: generate snake.exe
        uses: Platane/snk@v2.1.0
        with:
          output: exe
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.exe?palette=github-dark

      - name: push snake.exe to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
